# Generated by Django 5.1.5 on 2025-05-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_page_options_page_created_page_is_published_and_more'),
    ]

    operations = [
    ]
