# Generated by Django 5.1.5 on 2025-05-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20250529_0502'),
    ]

    operations = [
    ]
