# Generated by Django 5.1.5 on 2025-05-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_initial_page_model'),
    ]

    operations = [
    ]
