# Generated by Django 5.1.5 on 2025-05-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_category_page_excerpt_page_featured_image_and_more'),
    ]

    operations = [
    ]
