# Generated by Django 5.1.5 on 2025-05-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_auto_20250529_0746'),
    ]

    operations = [
    ]
