# Generated by Django 5.1.5 on 2025-05-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('grade', models.FloatField(verbose_name='Оценка')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
